# @name Post new event
POST http://localhost:8080/products
Content-Type: application/json

{
  "title": "New Product 2",
  "price": 1293,
  "quantity": 1232
}


> {%

    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });

%}